### ISSUE TITLE
Daily Run broken due to awscli2 in term-apply img

### ISSUE THREAD

**Issue by sarcasticadmin** [Nebulaworks/nix-garage#54]
## Description

Something seems to be broken with `awscli2` and its dependency override `awscrt` (https://github.com/Nebulaworks/nix-garage/runs/6064428466?check_suite_focus=true#step:4:22212) This originally started 3 days ago

Error results in the following in the action logs:

```
-- Go not found. Disabling some code generation and using pre-generated code in generated-src/
-- Perl not found. Disabling some code generation and using pre-generated code in generated-src/
-- Test stdalign_check.c passed, enabling AWS_LC_STDALIGN_AVAILABLE
-- Test builtin_swap_check.c passed, enabling AWS_LC_BUILTIN_SWAP_SUPPORTED
-- The ASM compiler identification is GNU
-- Found assembler: /nix/store/58pwclg9yr437h0pfgrnbd0jis8fqasd-gcc-wrapper-11.2.0/bin/gcc
Copying platform assembly files from /tmp/nix-build-python3.9-awscrt-0.12.4.drv-0/awscrt-0.12.4/crt/aws-lc/generated-src/linux-x86_64/crypto/ to /tmp/nix-build-python3.9-awscrt-0.12.4.drv-0/awscrt-0.12.4/build/deps/aws-lc/crypto
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/nix-build-python3.9-awscrt-0.12.4.drv-0/awscrt-0.12.4/build/deps/aws-lc
/nix/store/28lglq8yh2d19dq3rfsksrzijc5yljrl-cmake-3.22.3/bin/cmake --build ./ --config RelWithDebInfo --target install --parallel 2
[  0%] Built target global_target
Scanning dependencies of target fipsmodule
[  1%] Building C object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/fips_shared_support.c.o
[  1%] Building C object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/bcm.c.o
[  1%] Building ASM object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/aesni-gcm-x86_64.S.o
[  2%] Building ASM object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/aesni-x86_64.S.o
[  2%] Building ASM object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/ghash-ssse3-x86_64.S.o
[  2%] Building ASM object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/ghash-x86_64.S.o
[  3%] Building ASM object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/md5-x86_64.S.o
[  3%] Building ASM object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/p256-x86_64-asm.S.o
[  4%] Building ASM object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/p256_beeu-x86_64-asm.S.o
[  4%] Building ASM object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/rdrand-x86_64.S.o
[  4%] Building ASM object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/rsaz-avx2.S.o
[  5%] Building ASM object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/sha1-x86_64.S.o
[  5%] Building ASM object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/sha256-x86_64.S.o
[  5%] Building ASM object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/sha512-x86_64.S.o
[  6%] Building ASM object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/vpaes-x86_64.S.o
[  6%] Building ASM object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/x86_64-mont5.S.o
[  7%] Building ASM object crypto/fipsmodule/CMakeFiles/fipsmodule.dir/x86_64-mont.S.o
In file included from /tmp/nix-build-python3.9-awscrt-0.12.4.drv-0/awscrt-0.12.4/crt/aws-lc/crypto/fipsmodule/bcm.c:104:
/tmp/nix-build-python3.9-awscrt-0.12.4.drv-0/awscrt-0.12.4/crt/aws-lc/crypto/fipsmodule/sha/sha256.c: In function ‘SHA224_Final’:
/tmp/nix-build-python3.9-awscrt-0.12.4.drv-0/awscrt-0.12.4/crt/aws-lc/crypto/fipsmodule/sha/sha256.c:122:10: error: ‘SHA256_Final’ accessing 32 bytes in a region of size 28 [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wstringop-overflow=-Werror=stringop-overflow=8;;]
  122 |   return SHA256_Final(out, ctx);
      |          ^~~~~~~~~~~~~~~~~~~~~~
/tmp/nix-build-python3.9-awscrt-0.12.4.drv-0/awscrt-0.12.4/crt/aws-lc/crypto/fipsmodule/sha/sha256.c:122:10: note: referencing argument 1 of type ‘uint8_t *’ {aka ‘unsigned char *’}
/tmp/nix-build-python3.9-awscrt-0.12.4.drv-0/awscrt-0.12.4/crt/aws-lc/crypto/fipsmodule/sha/sha256.c:171:20: note: in a call to function ‘SHA256_Final’
  171 | #define HASH_FINAL SHA256_Final
      |                    ^~~~~~~~~~~~
/tmp/nix-build-python3.9-awscrt-0.12.4.drv-0/awscrt-0.12.4/crt/aws-lc/crypto/fipsmodule/sha/../digest/md32_common.h:193:5: note: in expansion of macro ‘HASH_FINAL’
  193 | int HASH_FINAL(uint8_t out[HASH_DIGEST_LENGTH], HASH_CTX *c) {
      |     ^~~~~~~~~~
In function ‘SHA224_Final’,
    inlined from ‘SHA224’ at /tmp/nix-build-python3.9-awscrt-0.12.4.drv-0/awscrt-0.12.4/crt/aws-lc/crypto/fipsmodule/sha/sha256.c:100:3:
/tmp/nix-build-python3.9-awscrt-0.12.4.drv-0/awscrt-0.12.4/crt/aws-lc/crypto/fipsmodule/sha/sha256.c:122:10: error: ‘SHA256_Final’ accessing 32 bytes in a region of size 28 [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wstringop-overflow=-Werror=stringop-overflow=8;;]
  122 |   return SHA256_Final(out, ctx);
      |          ^~~~~~~~~~~~~~~~~~~~~~
/tmp/nix-build-python3.9-awscrt-0.12.4.drv-0/awscrt-0.12.4/crt/aws-lc/crypto/fipsmodule/sha/sha256.c: In function ‘SHA224’:
/tmp/nix-build-python3.9-awscrt-0.12.4.drv-0/awscrt-0.12.4/crt/aws-lc/crypto/fipsmodule/sha/sha256.c:122:10: note: referencing argument 1 of type ‘uint8_t *’ {aka ‘unsigned char *’}
/tmp/nix-build-python3.9-awscrt-0.12.4.drv-0/awscrt-0.12.4/crt/aws-lc/crypto/fipsmodule/sha/sha256.c:171:20: note: in a call to function ‘SHA256_Final’
  171 | #define HASH_FINAL SHA256_Final
      |                    ^~~~~~~~~~~~
/tmp/nix-build-python3.9-awscrt-0.12.4.drv-0/awscrt-0.12.4/crt/aws-lc/crypto/fipsmodule/sha/../digest/md32_common.h:193:5: note: in expansion of macro ‘HASH_FINAL’
  193 | int HASH_FINAL(uint8_t out[HASH_DIGEST_LENGTH], HASH_CTX *c) {
      |     ^~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [crypto/fipsmodule/CMakeFiles/fipsmodule.dir/build.make:76: crypto/fipsmodule/CMakeFiles/fipsmodule.dir/bcm.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:223: crypto/fipsmodule/CMakeFiles/fipsmodule.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
Traceback (most recent call last):
  File "/tmp/nix-build-python3.9-awscrt-0.12.4.drv-0/awscrt-0.12.4/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 286, in <module>
    setuptools.setup(
  File "/nix/store/xi8ha1k3mjpmnmmi5fp7fmq41f2wwghm-python3.9-setuptools-61.2.0/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/xi8ha1k3mjpmnmmi5fp7fmq41f2wwghm-python3.9-setuptools-61.2.0/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/nix/store/xi8ha1k3mjpmnmmi5fp7fmq41f2wwghm-python3.9-setuptools-61.2.0/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/nix/store/xi8ha1k3mjpmnmmi5fp7fmq41f2wwghm-python3.9-setuptools-61.2.0/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/nix/store/xi8ha1k3mjpmnmmi5fp7fmq41f2wwghm-python3.9-setuptools-61.2.0/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/nix/store/xi8ha1k3mjpmnmmi5fp7fmq41f2wwghm-python3.9-setuptools-61.2.0/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/nix/store/gh9brapzy0br7318g8zybd4q8366vrab-python3.9-wheel-0.37.1/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/nix/store/xi8ha1k3mjpmnmmi5fp7fmq41f2wwghm-python3.9-setuptools-61.2.0/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/nix/store/xi8ha1k3mjpmnmmi5fp7fmq41f2wwghm-python3.9-setuptools-61.2.0/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/nix/store/xi8ha1k3mjpmnmmi5fp7fmq41f2wwghm-python3.9-setuptools-61.2.0/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/nix/store/xi8ha1k3mjpmnmmi5fp7fmq41f2wwghm-python3.9-setuptools-61.2.0/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/nix/store/xi8ha1k3mjpmnmmi5fp7fmq41f2wwghm-python3.9-setuptools-61.2.0/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/nix/store/xi8ha1k3mjpmnmmi5fp7fmq41f2wwghm-python3.9-setuptools-61.2.0/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/nix/store/xi8ha1k3mjpmnmmi5fp7fmq41f2wwghm-python3.9-setuptools-61.2.0/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "setup.py", line 208, in run
    self._build_dependency(lib)
  File "setup.py", line 201, in _build_dependency
    subprocess.check_call(build_cmd)
  File "/nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/28lglq8yh2d19dq3rfsksrzijc5yljrl-cmake-3.22.3/bin/cmake', '--build', './', '--config', 'RelWithDebInfo', '--target', 'install', '--parallel', '2']' returned non-zero exit status 2.
error: builder for '/nix/store/dkc8f19bwhawl042qr6ngpbf4kh8qdbj-python3.9-awscrt-0.12.4.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/ha52wgqp68izrk7bx6yp3r67wn6aqjhq-awscli2-2.4.23.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6di3ac98m7nfg2i6mzgjr0p8km265wq5-docker-layer-term-apply.drv' failed to build
error: 1 dependencies of derivation '/nix/store/i79zlpbzv9k6lngrg3hc2xgvpidqpcil-docker-image-term-apply.tar.gz.drv' failed to build
Error: Process completed with exit code 100.
```

A potential fix seems to have landed today in upstream nixpkgs: https://github.com/NixOS/nixpkgs/pull/169441

AC:
- Wait to see if `Daily Run` CI completes successfully tonight
- Fix accordingly if daily run continues to fail

**Comment by Mic92** [comment]
Fix is in master.
